# Generated by Django 4.1.2 on 2022-10-14 01:31

from django.db import migrations, models
import network.models


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='profileImage',
            field=models.ImageField(blank=True, null=True, upload_to=network.models.filepathP),
        ),
        migrations.AlterField(
            model_name='post',
            name='headline',
            field=models.CharField(blank=True, max_length=500),
        ),
    ]
