# Generated by Django 4.0.6 on 2022-11-16 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0004_comment_timestamp_post_timestamp'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='posts',
            field=models.ManyToManyField(blank=True, related_name='User_post', to='network.post'),
        ),
    ]
