# Generated by Django 4.0.6 on 2022-11-27 05:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0005_user_posts'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='posts',
        ),
        migrations.AddField(
            model_name='user',
            name='biography',
            field=models.CharField(blank=True, max_length=150),
        ),
    ]
