# Generated by Django 4.1.2 on 2023-01-09 04:39

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0008_alter_userfollowing_timestap'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userfollowing',
            name='timestap',
            field=models.DateTimeField(default=datetime.datetime(2023, 1, 9, 4, 39, 48, 202954, tzinfo=datetime.timezone.utc)),
        ),
    ]
